# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.analyse_barcodes <- function(metric, barcodes, cores, cost_sub, cost_indel) {
    .Call('DNABarcodes_analyse_barcodes', PACKAGE = 'DNABarcodes', metric, barcodes, cores, cost_sub, cost_indel)
}

.barcode_set_distances <- function(metric, barcodes, cores, cost_sub, cost_indel) {
    .Call('DNABarcodes_barcode_set_distances', PACKAGE = 'DNABarcodes', metric, barcodes, cores, cost_sub, cost_indel)
}

.code_falsification <- function(str_barcodes, d, metric, cores) {
    .Call('DNABarcodes_code_falsification', PACKAGE = 'DNABarcodes', str_barcodes, d, metric, cores)
}

.create_dnabarcodes <- function(n, d, metric, generation, filter_triplets, filter_gc, filter_self_complementary, str_pool, iterations, population, cores, use_cache, cost_sub, cost_indel) {
    .Call('DNABarcodes_create_dnabarcodes', PACKAGE = 'DNABarcodes', n, d, metric, generation, filter_triplets, filter_gc, filter_self_complementary, str_pool, iterations, population, cores, use_cache, cost_sub, cost_indel)
}

.test_distance <- function(str_seq1, str_seq2) {
    .Call('DNABarcodes_test_distance', PACKAGE = 'DNABarcodes', str_seq1, str_seq2)
}

.create_pool <- function(n, filter_triplets, filter_gc, filter_self_complementary, cores) {
    .Call('DNABarcodes_create_pool', PACKAGE = 'DNABarcodes', n, filter_triplets, filter_gc, filter_self_complementary, cores)
}

.demultiplex <- function(barcodes, reads, metric, cost_sub, cost_indel) {
    .Call('DNABarcodes_demultiplex', PACKAGE = 'DNABarcodes', barcodes, reads, metric, cost_sub, cost_indel)
}

.distance <- function(sequence1, sequence2, metric, cost_sub, cost_indel) {
    .Call('DNABarcodes_distance', PACKAGE = 'DNABarcodes', sequence1, sequence2, metric, cost_sub, cost_indel)
}

